DROP TABLE IF EXISTS Winkel;
DROP TABLE IF EXISTS Auteur;
DROP TABLE IF EXISTS Uitgever;
DROP TABLE IF EXISTS Boek;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Voorraad;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Item;


CREATE TABLE Winkel (
	filiaalnr	INTEGER 		NOT NULL UNIQUE,
	adres   	VARCHAR(255) 	NOT NULL,
	plaats  	VARCHAR(255) 	NOT NULL,
	telnr		INTEGER 		NOT NULL,
	PRIMARY KEY	(filiaalnr)
);

CREATE TABLE Auteur (
	id 			INTEGER 		NOT NULL UNIQUE,
	naam		VARCHAR(255) 	NOT NULL,
	url			VARCHAR(255) 	NOT NULL,
	PRIMARY KEY	(id)
);

CREATE TABLE Uitgever (
	id 			INTEGER 		NOT NULL UNIQUE,
	naam		VARCHAR(255) 	NOT NULL,
	adres   	VARCHAR(255) 	NOT NULL,
	plaats  	VARCHAR(255) 	NOT NULL,
	telnr		INTEGER 		NOT NULL,
	url			VARCHAR(255) 	NOT NULL,
	PRIMARY KEY	(id)
);

CREATE TABLE Boek (
	ISBN		INTEGER			NOT NULL,
	titel		VARCHAR(255)	NOT NULL,
	uitgavejaar	INTEGER 		NOT NULL,
	prijs		INTEGER 		NOT NULL,
	auteurId	INTEGER 		NOT NULL UNIQUE,
	uitgeverId	INTEGER			NOT NULL UNIQUE,
	PRIMARY KEY	(ISBN)
);

CREATE TABLE Account (
	email		VARCHAR(255) 	NOT NULL UNIQUE,
	naam		VARCHAR(255) 	NOT NULL,
	adres   	VARCHAR(255) 	NOT NULL,
	plaats  	VARCHAR(255) 	NOT NULL,
	telnr		INTEGER,
	PRIMARY KEY	(email)
);

CREATE TABLE Voorraad (
	id  		INTEGER 		NOT NULL UNIQUE,
	aantal		INTEGER 		NOT NULL,
	winkelFilnr	INTEGER 		NOT NULL UNIQUE,
	boekISBN	INTEGER 		NOT NULL UNIQUE,
	PRIMARY KEY	(id)
);

CREATE TABLE Cart (
	bestelnr	INTEGER 		NOT NULL UNIQUE,
	accountEmail VARCHAR(255) 	NOT NULL UNIQUE,
	PRIMARY KEY	(bestelnr)
);

CREATE TABLE Item (
	id 			INTEGER			NOT NULL UNIQUE,
	aantal      INTEGER			NOT NULL,
	boekISBN	INTEGER 		NOT NULL UNIQUE,
	cartBestelnr INTEGER 		NOT NULL UNIQUE,
	PRIMARY KEY	(id)
);


ALTER TABLE Boek 		ADD CONSTRAINT FK_AuteurId 		FOREIGN KEY (auteurId) 		REFERENCES Auteur(id);
ALTER TABLE Boek 		ADD CONSTRAINT FK_UitgeverId 	FOREIGN KEY (uitgeverId) 	REFERENCES Uitgever(id);

ALTER TABLE Voorraad	ADD CONSTRAINT FK_WinkelFilnr	FOREIGN KEY (winkelFilnr)	REFERENCES Winkel(filiaalnr);
ALTER TABLE Voorraad	ADD CONSTRAINT FK_BoekISBN		FOREIGN KEY (boekISBN)		REFERENCES Boek(ISBN);

ALTER TABLE Cart		ADD CONSTRAINT FK_AccountEmail	FOREIGN KEY (accountEmail)	REFERENCES Account(email);

ALTER TABLE Item		ADD CONSTRAINT FK_BoekISBN_Item FOREIGN KEY	(boekISBN)		REFERENCES Boek(ISBN);
ALTER TABLE Item		ADD CONSTRAINT FK_CartBestelnr	FOREIGN KEY (cartBestelnr)	REFERENCES Cart(bestelnr);



INSERT INTO Winkel		VALUES	(1, 'Rokin 9',			'Amsterdam',	0205231481	);
INSERT INTO Winkel		VALUES	(2, 'Oudegracht 112-b',	'Utrecht',		0302335200	);
INSERT INTO Winkel		VALUES	(3, 'Coolsingel 129',	'Den Haag',		0104132070	);
INSERT INTO Winkel		VALUES	(4, 'Kerkstraat 27',	'Den Bosch',	0733020100	);

INSERT INTO Accout		VALUES	('a_devries@adelaarsnest.nl',	'Arend de Vries',	'Adelaarsnest 12',	'Haarlem',	0612345678	);
INSERT INTO Accout		VALUES	('bboer@boeren.nl,',			'Bert Boer',		'Mesthoop 1',		'Dorp',		0623456789	);
INSERT INTO Accout		VALUES	(email,naam,adres,plaats,telnr);